Build TestServer on Spring boot
Kims-DeveloperGroup/gaming-server pull request #1
Opened 2019-03-17 11:02 UTC by feel2174

2019-03-17 15:34 UTC, JasonKyeongsikKim commented on SpringbootServer/.mvn/wrapper/MavenWrapperDownloader.java
> +/*
이 파일 왜 넣은거냐?

2019-03-17 15:34 UTC, JasonKyeongsikKim commented on SpringbootServer/.mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.0/apache-maven-3.6.0-bin.zip
이것도 왜 넣은거야

2019-03-17 15:35 UTC, JasonKyeongsikKim commented on SpringbootServer/mvnw
> +#!/bin/sh
이런거 push 하지 말고 다 gitignore에 넣어

2019-03-17 15:36 UTC, JasonKyeongsikKim commented on SpringbootServer/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
pom.xml SpringbootServer 안에다가 하는게 아니라 프로젝트root path에 있어야해.

2019-03-17 15:37 UTC, JasonKyeongsikKim commented on SpringbootServer/src/main/java/com/example/demo/DemoApplication.java
> +package com.example.demo;
SpringbootServer라는 디렉토리를 따로 넣을 필요가 없어. 지금 어플리케이션 하나 만드는거자나.

2019-03-17 15:38 UTC, JasonKyeongsikKim commented on SpringbootServer/src/main/resources/static/index.html
> +</html>
지금 어플리케이션은 서버사이드 어플리케이션이야 페이지 띄울일 없어.

2019-03-17 15:38 UTC, JasonKyeongsikKim commented on SpringbootServer/src/test/java/com/example/demo/DemoApplicationTests.java
> +
이건 어떤 목적이야?

2019-03-17 15:39 UTC, JasonKyeongsikKim commented on SpringbootServer/src/main/java/com/example/demo/DemoApplication.java
> +public class DemoApplication {
어플리케이션 이름으로 지어. Demo용 Application 아니자나.

2019-03-17 15:40 UTC, JasonKyeongsikKim commented on SpringbootServer/pom.xml
> +		</dependency>
이거 빼자

2019-03-17 15:40 UTC, JasonKyeongsikKim commented on SpringbootServer/pom.xml
> +		</dependency>
redis도 빼자. 필요한거만 넣고 시작해.

2019-03-17 15:40 UTC, JasonKyeongsikKim commented on SpringbootServer/pom.xml
> +		</dependency>
우리 jdbc 사용안할거야.

2019-03-17 15:41 UTC, JasonKyeongsikKim commented on SpringbootServer/pom.xml
> +			<scope>test</scope>
이건 나도 모르는 라이브러린데 목적이 뭐야?

2019-03-17 15:41 UTC, JasonKyeongsikKim commented on SpringbootServer/pom.xml
> +				<executions>
이것도 목적이?

2019-03-17 15:43 UTC, JasonKyeongsikKim commented on SpringbootServer/src/main/java/com/example/demo/DemoApplication.java
> +package com.example.demo;
src/main/java 로 가면돼. 그리고 페키지 example로 하지 말고 네이밍 하자. 
com.kims.gaming.server 정도로 하자.

2019-03-17 15:47 UTC, JasonKyeongsikKim commented on SpringbootServer/pom.xml
> +			<scope>test</scope>
<dependencies>
                <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter</artifactId>
                </dependency>

                <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-test</artifactId>
                        <scope>test</scope>
                </dependency>
        </dependencies>

        <build>
                <plugins>
                        <plugin>
                                <groupId>org.springframework.boot</groupId>
                                <artifactId>spring-boot-maven-plugin</artifactId>
                        </plugin>
                </plugins>
        </build>

2019-03-17 15:47 UTC, JasonKyeongsikKim commented on SpringbootServer/pom.xml
> +			<scope>test</scope>
위에 정도로 디펜던시 잡고 시작하는게 좋을거 같아.필요한건 그때 그때 추가하면서 해보자.

2019-03-17 15:49 UTC, JasonKyeongsikKim commented
잘 세팅했어. 근데 불필요한 파일들도 같이 올라와서 PR이 전체적으로 좀 더럽네.....ㅋㅋㅋ보기 힘들어.

2019-03-17 15:50 UTC, rica-v3 requested changes
수정 요망

2019-03-17 15:51 UTC, JasonKyeongsikKim commented
아 그리고 요청 들어온건 페이지 띄우라고 한게 아니야.

일단 셋업하는 부분만 수정해서 머지하고 요청/응답은 다시 얘기해보자.

2019-03-17 16:53 UTC, feel2174 commented on SpringbootServer/src/test/java/com/example/demo/DemoApplicationTests.java
> +
스프링부트 소스를 기본대로 받고 서버구동하면 모두 들어있는 파일인데 필요한 파일, 필요없는 파일은  정리해야겠다

2019-03-18 07:25 UTC, JasonKyeongsikKim commented on mvnw.cmd
> +
이 파일은 필요 없을거 같아. 지금 수업 중인데 테스트용이니까 무시해

2019-03-18 13:13 UTC, JasonKyeongsikKim commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
이것도 지워줘. 니 로컬에 깔린 메이븐 파일이자나. 프로젝트 파일이 아님

2019-03-18 13:14 UTC, JasonKyeongsikKim commented on pom.xml
> +	</dependencies>
여기 디펜던시들도 내가 리뷰 달아준대로 다 빼자.

2019-03-18 13:14 UTC, JasonKyeongsikKim commented on SpringbootServer/src/test/java/com/example/demo/DemoApplicationTests.java
> +
이것도 지우고.

2019-03-18 13:16 UTC, JasonKyeongsikKim commented
@feel2174 pom.xml에서 보면 뭔가 이것저것 많이 들었는데 다 지우고. 스프링부트 이니셜라이저로 만들었을때 처음 상태 그대로 맞춰.

그리고 너의 컴퓨터에 있는 메이븐 관련 세팅 파일들도 아직 그대로임. 내가 지우라고 한거 다 지우고.

2019-03-18 13:17 UTC, JasonKyeongsikKim commented
@feel2174 아 그리고 하나 더 코멘트 하자면, 근거 없이 들어간 파일들이나 설정들이 너무 많아. 왜 들어가야 하는지 이유를 모르거나 없다면 추가를 하면 안돼.  필요 있다고 생각되는 파일들이나 설정들만 집어 넣어줘.

2019-03-18 14:19 UTC, merged