Springboot server
Kims-DeveloperGroup/gaming-server pull request #3
Opened 2019-03-18 14:45 UTC by feel2174

2019-03-21 12:15 UTC, JasonKyeongsikKim commented on pom.xml
> +
PR 주제랑 상관없는 불필요한 변경은 최대한 피하는게 좋아. 파일이 하나 더 생겼자나.

2019-03-21 12:16 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/ServerApplication.java
> +    }
이 기괴한 코드 포매팅은 뭐냐.

2019-03-21 12:16 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/ServerApplication.java
> +@Component
이건 빈이 아니니까 Component 빼도 됨

2019-03-21 12:17 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +public class ServerApplicationService {
쓸모없는 스페이스 만들지마

2019-03-21 12:18 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +        boolean listen = true;
논리적인 단위로 코드를 스페이스로 나눠주는건 좋은데 

스페이스가 너무 잦으면 안좋고, 특히 위에 처럼 2줄  있는건 좋지 않아.

2019-03-21 12:18 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +
스페이스

2019-03-21 12:18 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +
스페이스

2019-03-21 12:18 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +            byte buffer[] = new byte[1024];
스페이스

2019-03-21 12:19 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +        System.out.println("연결 대기중");
클래스 상단에 @Sl4j 넣고 
log.info
log.warn
log.debug 로 로거 함수 쓸수 있어

System.out 사용하지마.

2019-03-21 12:19 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/ServerApplication.java
> +
스페이스

2019-03-21 12:20 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +            System.out.println("Cleint : " + msg);
로거(logger)로 바꿔

2019-03-21 12:23 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +public class ServerApplicationService {
ServerApplicationService 이름이 작동하는 내용이랑 맞는가에 대해서 생각해봐. 

지금 너가 구현한 기능은 사용자가 접속하는거  받아주는 역할이자나.
나라면 PlayerConnectionListener 정도로 할거 같아.

2019-03-21 12:25 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +    @Autowired
여기에 왜 Autowired를 붙인거야? Autowired 는 정의된 빈 객체 가져오는 어노테이션 이자나.

2019-03-21 12:27 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +    public void run() throws IOException {
서버를 run 한다는 의미인거 같은데, 이미 서버는 돌고있자나. 

openConnection 이나 listenPlayerConnection 가 더 어울리는 이름같아.

2019-03-21 12:32 UTC, rica-v3 requested changes
수정요망

2019-03-21 12:36 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +        while (listen) {
while 이랑 괄화 사이에 띄워쓰기 노노

2019-03-21 12:37 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/ServerApplication.java
> +
노 줄바꿈

2019-03-21 13:05 UTC, feel2174 commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +    @Autowired
정확한 원인은 더 알아봐야겠으나, Autowired를 없애면 어플리케이션이 죽어버려.

2019-03-21 13:24 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/PlayerConnectionListener.java
> +    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(PlayerConnectionListener.class);
@feel2174 어노테이션으로 해결해....이거 아님

2019-03-21 13:24 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/PlayerConnectionListener.java
> +            System.out.println("Cleint : " + msg);
기껏 로거 달아놓고 이건 뭐임

2019-03-21 13:26 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/PlayerConnectionListener.java
> +        while(listen) {
빠져나가는 코드가 없는데?

2019-03-21 13:26 UTC, rica-v3 approved these changes
마이너한거 몇개 고치고 
로거는 어노테이션으로 해결해.

2019-03-21 13:30 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/ServerApplicationService.java
> +    @Autowired
너가 뭔가 잘못한거야
해결해봐.

2019-03-23 06:16 UTC, JasonKyeongsikKim commented on pom.xml
> +            <version>2.1.3.RELEASE</version>
이미 스프링부트 관련 dependency가 들어가잇는데 필요해?

2019-03-25 16:40 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/PlayerConnectionListener.java
> +            packet = new DatagramPacket(buf, buf.length, address, port);
줄임말 쓰지마.  차라리 buffer라고해

2019-03-25 16:43 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/PlayerConnectionListener.java
> +            log.info(msg);
들어온 메시지만 띡하고 찍어두면 나중에 이게 뭔지 어떻게 알아. 의미있는 메시지를 만들어 봐. 
로그는 너가 그냥 콘솔창에 잘 찍히나 확인하는 용도가 아니야. 나중에 다른 사람이 봤을때 저게 뭘 의미하는지 알수 있게 작성해봐

2019-03-25 16:45 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/PlayerConnectionListener.java
> +            if (receivePacket == null) {
null 레퍼런스는 왠만하면 사용하지마. 
커넥션 끊는 케이스는 timeout을 걸거나 disconnected 라는 메시지가 클라에서 올때 종료하는걸로 해.

2019-03-25 16:45 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/PlayerConnectionListener.java
>              json.put("status", "connnected");
이것도 지금 스트링으로 밖아놨는데 class랑 enum 사용해서 정의해두고 사용해봐.

2019-03-25 16:47 UTC, JasonKyeongsikKim commented on src/main/java/com/kims/gaming/server/service/PlayerConnectionListener.java
> +            DatagramPacket sendPacket = new DatagramPacket(buf, buf.length, address, port);
이건 마이너하긴한데 변수명은 명사로 하는게 규칙이자나. sendDataPacket은 동사자나. receivePacket도

2019-03-25 16:49 UTC, rica-v3 requested changes
DataPacket 바이트로 Serialize ,Deserialize 하는 코드 통신하면 자주 사용할거 같은데 메쏘드나 클래스로 뺏 서 사용하는것도 고려해봐.

2019-03-28 12:20 UTC, merged